"""Add sold field

Revision ID: 8ae0e8338ece
Revises: d79c880bb226
Create Date: 2025-03-13 15:54:52.134961

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ae0e8338ece"
down_revision: Union[str, None] = "d79c880bb226"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("show", sa.String(), nullable=True),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("sold", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickets")
    # ### end Alembic commands ###
